export const SliderData = [
    {
        image:'/DSC_0339.JPG'
    },
    {
        image:'/DSC_0340.JPG'
    },
    {
        image:'/DSC_0341.JPG'
    },
    {
        image:'/DSC_0343.JPG'
    },
    {
        image:'/DSC_0344.JPG'
    },
    {
        image:'/DSC_0345.JPG'
    }
]